id: PD1F03B2D
initial_creation_type: ocr
source_metadata:
  volumes:
    2ecf4bd50b8b460abae924d9293fbfd6:
      base_file: v077.txt
      image_group_id: I1PD95922
      title: སུམ་ཅུ་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1517
      volume_number: 77
